### ISSUE TITLE
Define PO and Scrum master

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [martchellop/Bitmask_knights#1]

**Comment by BrunoGomesCoelho** [comment]
We still need to define the Scrum Master

**Comment by martchellop** [comment]
You are the Scrum Master

**Comment by BrunoGomesCoelho** [comment]
I think a vote would be nice

**Comment by martchellop** [comment]
@BrunoGomesCoelho That's precisely why you are the PO

**Comment by BrunoGomesCoelho** [comment]
@matheushjs I think this was also chosen this meeting, if you could add it to the meeting summary would be nice so I can close this.
