### ISSUE TITLE
Choose a Continous Integration system

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [martchellop/Bitmask_knights#7]
There are two main, wide-adopted alternatives: Travis-CI and Jenkins
Me and @LTKills have had personal exprience with Travis and it seemed quite easy to use, but I think both would be acceptable.

Here is a more in depth comparison:
https://stackshare.io/stackups/buildbot-vs-jenkins-vs-travis-ci

- [x] Bruno
- [x] Gabriel
- [x] Marcelo
- [ ] Saldanha
- [ ] Silencio
- [ ] Thiago

Jenkins:     0
Travis-CI:   3

**Comment by martchellop** [comment]
I'm going to vote for Jenkins just 'cause more people use it

**Comment by BrunoGomesCoelho** [comment]
Same vote, but because I want to learn something different

**Comment by martchellop** [comment]
I was looking in the Jenkins documentation and it seems a lot of work to set it up, are you sure you want to use it?

**Comment by BrunoGomesCoelho** [comment]
@martchellop It seems like your right, oficially changing my preference to Travis since it is quite easy

**Comment by martchellop** [comment]
@BrunoGomesCoelho Same

**Comment by matheushjs** [comment]
Both documentations are overwhelmingly big.

While I'm interested in learning how to use a software testing utility (for other things besides our project), I don't think all members of our group **should** be made to learn it.

Should we adopt continuous integration, can a single person be in change of its usage?

**Comment by BrunoGomesCoelho** [comment]
I wouldnt mind being in charge of it (also its much easier than it seems and I think @LTKills wouldnt mind helping me).

**Comment by LTKills** [comment]
I'm up for it :smiley:
