### ISSUE TITLE
Test telegram bot

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [martchellop/Bitmask_knights#9]

**Comment by BrunoGomesCoelho** [comment]
ITS ALIVE https://giphy.com/explore/its-alive

**Comment by martchellop** [comment]
@BrunoGomesCoelho Just testing the reply from telegram

**Comment by BrunoGomesCoelho** [comment]
@BrunoGomesCoelho Trying out a telegram comment

**Comment by martchellop** [comment]
@BrunoGomesCoelho Trying to use *Markdown* syntax in the comment
